# Header
menu:
  首页: eyutongling.github.io 
  代码仓库: https://github.com/eyutongling
  简历: 
  捐赠名单: /donors
  留言板: /about
  

# Content
excerpt_link: 更多内容
prev: 上一页
next: 下一页
reply: 评论
share: 分享
fancybox: true

# Sidebar
widgets:
- about
#- support
- music
- recent_posts
- archive
- category
- link
- account

# Miscellaneous
google_analytics: 
favicon: http://7u2hdm.com1.z0.glb.clouddn.com/favicon.ico
baidu_site_verification: SXV214EKfj
bing_site_verification: 9E9EA92F7E5327E1FE8A5196D5253664
music: http://fs.web.kugou.com/4c78f041b8a023ef9a492d4076a569e4/59bfbca0/G110/M0B/1B/18/rg0DAFm7sViAOEMIAElWs9mJ7is815.mp3